server:
  port: 8080
  servlet:
    context-path: "/ho-api"
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/hotel?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
mybatis:
  type-aliases-package: classpath*:cn.mafangui.hotel.entity
  mapper-locations: classpath*:mybatis/mapper/*.xml

